# Generated by Django 4.0.2 on 2022-02-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
