# Generated by Django 4.0.2 on 2022-02-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_phone_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_token',
        ),
    ]
