# Generated by Django 4.0.2 on 2022-02-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_client_phone_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.AddField(
            model_name='client',
            name='uname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
