# Generated by Django 4.0.2 on 2022-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_created_at_client_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='uname',
            new_name='username',
        ),
        migrations.AddField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
