# Generated by Django 4.0.2 on 2022-02-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_rename_uname_client_username_client_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_token',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
