# Generated by Django 4.0.2 on 2022-02-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='contact_token',
            new_name='code',
        ),
    ]
