# Generated by Django 4.0.2 on 2022-03-24 14:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0022_alter_schedule_weekday_delete_patientcheckup'),
        ('patients', '0020_chiefcomplaint_unicode_presentillness_unicode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('unicode', models.CharField(max_length=300, null=True)),
                ('checkup_date', models.DateField(blank=True)),
                ('checkup_time', models.TimeField(blank=True)),
                ('status', models.CharField(choices=[('none', 'None'), ('cancelled', 'Cancelled'), ('done', 'Done')], max_length=100)),
                ('statement', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
