# Generated by Django 4.0.2 on 2022-03-24 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0022_alter_schedule_weekday_delete_patientcheckup'),
        ('appointments', '0002_rename_checkup_appoinment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinment',
            name='checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='checkup_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='appoinment',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='none', max_length=100),
        ),
    ]
