# Generated by Django 4.0.2 on 2022-03-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appoinment_checkup_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinment',
            old_name='checkup_time',
            new_name='checkup_end',
        ),
        migrations.AddField(
            model_name='appoinment',
            name='checkup_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
