# Generated by Django 4.0.2 on 2022-03-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_rename_checkup_time_appoinment_checkup_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
