# Generated by Django 4.0.2 on 2022-03-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_client_skinproblem_pulmonary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentillness',
            name='illness_image',
        ),
        migrations.RemoveField(
            model_name='presentillness',
            name='patient',
        ),
        migrations.CreateModel(
            name='PresentIllnessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_image', models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='profiles/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
