# Generated by Django 4.0.2 on 2022-03-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_presentillness_illness_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionalhistory',
            old_name='difficulties',
            new_name='difficulties_activities',
        ),
        migrations.RenameField(
            model_name='functionalhistory',
            old_name='difficulties_devices',
            new_name='difficulties_assistance',
        ),
        migrations.RenameField(
            model_name='musculoskeletal',
            old_name='neurologic_weakness',
            new_name='weakness',
        ),
        migrations.RemoveField(
            model_name='neurologic',
            name='musculoskeletal_none',
        ),
        migrations.RemoveField(
            model_name='presentillness',
            name='affects_grooming',
        ),
        migrations.AddField(
            model_name='adultillness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='breasts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cardiovascular',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='chiefcomplaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='childhoodillness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='endocrine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='functionalhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gastrointestinal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='generalsystem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='genitourinary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gynecologic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='heent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historyofimmunization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='musculoskeletal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='neurologic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='personalandsocialhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='presentillness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='presentillnessimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pulmonary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skinproblem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('separated', 'Separated'), ('widowed', 'Widowed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='how_often_drugs',
            field=models.CharField(blank=True, choices=[('everyday', 'Everyday'), ('most days of the week', 'Most days of the week'), ('1-2x per week', '1-2x per week'), ('every month', 'Every month'), ('occasional', 'Occasional')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='presentillnessimage',
            name='illness_image',
            field=models.ImageField(blank=True, null=True, upload_to='illnesses/'),
        ),
    ]
