# Generated by Django 4.0.2 on 2022-03-03 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_difficulties_functionalhistory_difficulties_activities_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breasts',
            new_name='Breast',
        ),
    ]
