# Generated by Django 4.0.2 on 2022-03-03 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_rename_breasts_breast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
