# Generated by Django 4.0.2 on 2022-03-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalandsocialhistory',
            name='course_year_levl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
