# Generated by Django 4.0.2 on 2022-03-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_personalandsocialhistory_course_year_levl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionalhistory',
            old_name='difficulties_in_things',
            new_name='difficulties_in_complicated',
        ),
        migrations.RemoveField(
            model_name='functionalhistory',
            name='affects_grooming',
        ),
    ]
