# Generated by Django 4.0.2 on 2022-03-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_rename_difficulties_in_things_functionalhistory_difficulties_in_complicated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functionalhistory',
            old_name='walk_alone',
            new_name='assistive_walking',
        ),
    ]
