# Generated by Django 4.0.2 on 2022-03-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_rename_walk_alone_functionalhistory_assistive_walking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neurologic',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Musculoskeletal',
        ),
        migrations.DeleteModel(
            name='Neurologic',
        ),
    ]
