# Generated by Django 4.0.2 on 2022-03-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_remove_neurologic_patient_delete_musculoskeletal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neurologic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbness', models.BooleanField()),
                ('weakness', models.BooleanField()),
                ('needle_sensation', models.BooleanField()),
                ('changes_in_mood', models.BooleanField()),
                ('changes_in_memory', models.BooleanField()),
                ('tremors', models.BooleanField()),
                ('seizures', models.BooleanField()),
                ('neurologic_none', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Musculoskeletal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joints_muscle_pain', models.BooleanField()),
                ('stiffness', models.BooleanField()),
                ('motion_limitation', models.BooleanField()),
                ('muscle_atrophy', models.BooleanField()),
                ('muscle_hypertrophy', models.BooleanField()),
                ('none', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
