# Generated by Django 4.0.2 on 2022-03-06 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_neurologic_musculoskeletal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neurologic',
            old_name='neurologic_none',
            new_name='none',
        ),
    ]
