# Generated by Django 4.0.2 on 2022-03-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_adultillness_unicode_breast_unicode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultillness',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='breast',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='cardiovascular',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='chiefcomplaint',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='childhoodillness',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='endocrine',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='familyhistory',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='functionalhistory',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='gastrointestinal',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='generalsystem',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='genitourinary',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='gynecologic',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='heent',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='historyofimmunization',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='musculoskeletal',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='neurologic',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='personalandsocialhistory',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='presentillness',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='presentillnessimage',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='pulmonary',
            old_name='unicode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='skinproblem',
            old_name='unicode',
            new_name='code',
        ),
    ]
