# Generated by Django 4.0.2 on 2022-03-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_remove_adultillness_code_remove_breast_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adultillness',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='breast',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='cardiovascular',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='endocrine',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='familyhistory',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='functionalhistory',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gastrointestinal',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='generalsystem',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='genitourinary',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='gynecologic',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='heent',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='historyofimmunization',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='musculoskeletal',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='neurologic',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='personalandsocialhistory',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='pulmonary',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='skinproblem',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
