# Generated by Django 4.0.2 on 2022-03-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_adultillness_unicode_breast_unicode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiefcomplaint',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='presentillness',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='presentillnessimage',
            name='unicode',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
