# Generated by Django 4.0.3 on 2022-04-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_chiefcomplaint_unicode_presentillness_unicode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentillness',
            name='activities_improves',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentillness',
            name='activities_worse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentillness',
            name='other_symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='presentillness',
            name='severity',
            field=models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=50, null=True),
        ),
    ]
