# Generated by Django 4.0.3 on 2022-04-02 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_presentillness_activities_improves_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalandsocialhistory',
            old_name='course_year_levl',
            new_name='course_year_level',
        ),
    ]
