# Generated by Django 4.0.3 on 2022-04-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_rename_course_year_levl_personalandsocialhistory_course_year_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalandsocialhistory',
            old_name='phyiscal_activity',
            new_name='physical_activity',
        ),
    ]
