# Generated by Django 4.0.3 on 2022-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_rename_phyiscal_activity_personalandsocialhistory_physical_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentillness',
            name='affect_activites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functionalhistory',
            name='needs_support',
            field=models.CharField(blank=True, choices=[('100%', '100%'), ('75%', '75%'), ('50%', '50%'), ('25%', '25%')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='gynecologic',
            name='miscarriages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gynecologic',
            name='pregnancies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='bottles_per_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='how_often_drinking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='how_often_drugs',
            field=models.CharField(blank=True, choices=[('everyday', 'Everyday'), ('most days of the week', 'Most days of the week'), ('1-2x per week', '1-2x per week'), ('every month', 'Every month'), ('occasional', 'Occasional')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='last_time_drugs',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='sticks_per_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='when_drugs_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='when_stop_smoking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personalandsocialhistory',
            name='years_smoking',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
