# Generated by Django 4.0.3 on 2022-04-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0025_alter_presentillness_how_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentillness',
            name='describe',
            field=models.TextField(blank=True, null=True),
        ),
    ]
