# Generated by Django 4.0.3 on 2022-05-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_rename_affect_activities_presentillness_affects_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentillness',
            name='how_long',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='presentillness',
            name='how_often',
            field=models.TextField(blank=True, null=True),
        ),
    ]
