# Generated by Django 3.2.13 on 2022-05-12 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_alter_presentillness_how_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentillness',
            name='symptoms_started',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
