# Generated by Django 4.0 on 2022-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_created_at_doctor_short_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
