# Generated by Django 4.0 on 2022-01-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_specialization_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, default='user-default.png', null=True, upload_to='doctors/'),
        ),
    ]
