# Generated by Django 4.0 on 2022-01-10 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_remove_doctor_is_active_remove_doctor_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='status',
        ),
    ]
