# Generated by Django 4.0.2 on 2022-03-13 14:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_chiefcomplaint_unicode_presentillness_unicode_and_more'),
        ('doctors', '0010_alter_doctor_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCheckup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('unicode', models.CharField(max_length=300, null=True)),
                ('checkup_date', models.DateField(blank=True)),
                ('checkup_time', models.TimeField(blank=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
