# Generated by Django 4.0.2 on 2022-03-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0019_schedule_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='limit',
        ),
        migrations.AddField(
            model_name='doctor',
            name='limit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
