# Generated by Django 4.0.2 on 2022-03-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_remove_schedule_limit_doctor_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='limit',
        ),
    ]
