# Generated by Django 4.0.2 on 2022-03-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_slot_remove_doctor_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=100),
        ),
        migrations.DeleteModel(
            name='PatientCheckup',
        ),
    ]
