# Generated by Django 4.0.3 on 2022-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0022_alter_schedule_weekday_delete_patientcheckup'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='clinic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
