# Generated by Django 4.0.3 on 2022-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_schedule_clinic'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='soft_delete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(max_length=100),
        ),
    ]
